image: java:latest

stages:
  - build
  - execute

build:
  stage: build
  script: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac App.java
  artifacts:
    paths:
     - App.*

execute:
  stage: execute
  script: /usr/lib/jvm/java-8-openjdk-amd64/bin/java App
test:
  stage: test
  script: /usr/lib/jvm/java-8-openjdk-amd64/bin/java AppTest
  
