image: java:latest
before_script:
  - 'which ssh-agent || ( apt-get updatey &&  -apt-get install openssh-client -y )'
  
stages:
  - build
  - execute
  - deploy

build:
  stage: build
  script: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac Hello.java
  artifacts:
    paths:
     - Hello.*

execute:
  stage: execute
  script: /usr/lib/jvm/java-8-openjdk-amd64/bin/java Hello
  
trigger:
  stage: trigger
  script:
  - "curl --request POST --form token=443a550d88c8dc4508a82ca9d9ee44 --form ref=master https://gitlab.com/api/v4/projects/{17389984}/trigger/pipeline"
  only:
  - master


deploy:dev:
  stage: deploy
  script:
    - bash deploy/deploy.sh
  only:
    - master
  dependencies:
    - execute
  when: manual



